### ISSUE TITLE
请问项目id怎么看？我就一个项目，尝试了0,1,2都提不出来

### ISSUE THREAD

**Issue by jiweizhangxu** [taishan1994/doccano_export#1]
![图片](https://user-images.githubusercontent.com/88191580/169219640-47dd3464-ee83-4471-9613-c60d9cd0381e.png)

**Comment by jiweizhangxu** [comment]
我明白了应该是网址后面的这个是
![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png)
但是同样试了3还是报相同错误
![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)

**Comment by taishan1994** [comment]
> 我明白了应该是网址后面的这个是 ![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png) 但是同样试了3还是报相同错误 ![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)

更新了一下doccano_export.py，可以再试试

**Comment by jiweizhangxu** [comment]
> > 我明白了应该是网址后面的这个是 ![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png) 但是同样试了3还是报相同错误 ![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)
> 
> 更新了一下doccano_export.py，可以再试试

大哥，没报错了，但是产生的json文件是个空文件，打开什么都没有，我一直开着doccano,也标好了
![图片](https://user-images.githubusercontent.com/88191580/169226244-1174890c-c6c2-4a7e-a88a-65a02dff6174.png)
![图片](https://user-images.githubusercontent.com/88191580/169226388-96446b32-e127-4b02-8b56-e952a0af3b3a.png)

**Comment by taishan1994** [comment]
> > > 我明白了应该是网址后面的这个是 ![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png) 但是同样试了3还是报相同错误 ![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)
> > 
> > 
> > 更新了一下doccano_export.py，可以再试试
> 
> 大哥，没报错了，但是产生的json文件是个空文件，打开什么都没有，我一直开着doccano,也标好了 ![图片](https://user-images.githubusercontent.com/88191580/169226244-1174890c-c6c2-4a7e-a88a-65a02dff6174.png) ![图片](https://user-images.githubusercontent.com/88191580/169226388-96446b32-e127-4b02-8b56-e952a0af3b3a.png)

打印一下span_data和relation_data看看。修改了代码，有一个confirm参数控制是否导出经过验证的。

**Comment by jiweizhangxu** [comment]
> span_data和relation_data

厉害啊，span_data 没毛病，写入但还是为空，我没有标关系，程序进不了for循环体，导致res为空，写入失败

![微信截图_20220520092529](https://user-images.githubusercontent.com/88191580/169430832-d84971c4-a6fe-4716-b219-8f60604c0f59.png)

![微信截图_20220520092614](https://user-images.githubusercontent.com/88191580/169430842-71618f62-8539-4fa5-867b-f642ad0a5bae.png)
![微信截图_20220520093304](https://user-images.githubusercontent.com/88191580/169430892-2b12bee3-5df4-4b92-ac8e-4cb9a56cc872.png)

**Comment by jiweizhangxu** [comment]
> > > > 我明白了应该是网址后面的这个是 ![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png) 但是同样试了3还是报相同错误 ![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)
> > > 
> > > 
> > > 更新了一下doccano_export.py，可以再试试
> > 
> > 
> > 大哥，没报错了，但是产生的json文件是个空文件，打开什么都没有，我一直开着doccano,也标好了 ![图片](https://user-images.githubusercontent.com/88191580/169226244-1174890c-c6c2-4a7e-a88a-65a02dff6174.png) ![图片](https://user-images.githubusercontent.com/88191580/169226388-96446b32-e127-4b02-8b56-e952a0af3b3a.png)
> 
> 打印一下span_data和relation_data看看。修改了代码，有一个confirm参数控制是否导出经过验证的。

我自己写个写入的程序，成功了，感谢大佬
听我说谢谢你~~，因为有你温暖了四季~~
![微信截图_20220520095338](https://user-images.githubusercontent.com/88191580/169433120-12bf2fdd-6efc-4760-963d-b2990affb71c.png)

**Comment by taishan1994** [comment]
> > > > > 我明白了应该是网址后面的这个是 ![图片](https://user-images.githubusercontent.com/88191580/169221398-ed443970-54cb-446b-8c97-47bc32c75e80.png) 但是同样试了3还是报相同错误 ![图片](https://user-images.githubusercontent.com/88191580/169221612-eb345dcd-ad3e-4179-8449-7cbec0b8a69f.png)
> > > > 
> > > > 
> > > > 更新了一下doccano_export.py，可以再试试
> > > 
> > > 
> > > 大哥，没报错了，但是产生的json文件是个空文件，打开什么都没有，我一直开着doccano,也标好了 ![图片](https://user-images.githubusercontent.com/88191580/169226244-1174890c-c6c2-4a7e-a88a-65a02dff6174.png) ![图片](https://user-images.githubusercontent.com/88191580/169226388-96446b32-e127-4b02-8b56-e952a0af3b3a.png)
> > 
> > 
> > 打印一下span_data和relation_data看看。修改了代码，有一个confirm参数控制是否导出经过验证的。
> 
> 我自己写个写入的程序，成功了，感谢大佬 听我说谢谢你~~，因为有你温暖了四季~~ ![微信截图_20220520095338](https://user-images.githubusercontent.com/88191580/169433120-12bf2fdd-6efc-4760-963d-b2990affb71c.png)

我也增加了两个参数用于控制输出关系的。供参考。

**Comment by DeadWa1ker7** [comment]
我的问题是 标记完实体后，导出数据里没有标签数据，实体为空。 这是为什么啊？
![image](https://user-images.githubusercontent.com/22993029/172999505-c9b88400-c54c-441a-a859-42153c175216.png)

**Comment by taishan1994** [comment]
> 我的问题是 标记完实体后，导出数据里没有标签数据，实体为空。 这是为什么啊？ ![image](https://user-images.githubusercontent.com/22993029/172999505-c9b88400-c54c-441a-a859-42153c175216.png)

你升级下doccano到最新的1.7.0版本

**Comment by DeadWa1ker7** [comment]
是的，升级1.7.0后问题就解决了。
